# BioSimSpace Travis CI configuration.

# Note that a 'language' variable isn't necessary since we run tests using
# a prebuilt Sire binary installation that comes with all necessary Python
# base packages. Travis will default to a Ruby VM, which comes with all
# required command-line utilities and works both on Linux and macOS.

# Only run CI against the testing branch.
branches:
  only:
    - testing

os:
  - linux
  - osx

notifications:
  email: false

# Disable Sire usage analytics and set paths for the Sire app, tests, and cache.
env:
  global:
    - SIRE_DONT_PHONEHOME=1
    - SIRE_SILENT_PHONEHOME=1
    - SIRE_DIR=$HOME/sire.app
    - TEST_DIR=$HOME/test
    - CACHE_DIR=$HOME/cache

# Set the cache location and increase the timeout to help avoid network issues.
cache:
  directories:
    - $HOME/cache
  timeout: 1000

# Download and unpack the binary Sire application and clone BioSimSpace tests.
# The latest binary is downloaded from siremol.org and stored in the build
# cache. This allows us to take advantage of super fast cloud-to-cloud file
# transfers and signficantly speed up the build process. Whenever a new
# version of Sire is released, we simply delete the cache from the Travis
# web interface and update the download links below.
before_install:
  - |
    if [ ! -f $CACHE_DIR/sire.run ]; then
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_linux.run -O $CACHE_DIR/sire.run
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_osx.run -O $CACHE_DIR/sire.run
        mkdir -p $HOME/.matplotlib
        echo "backend: TkAgg" > $HOME/.matplotlib/matplotlibrc
      fi
    fi
  - chmod a+x $CACHE_DIR/sire.run
  - unset DISPLAY && echo "$SIRE_DIR" | $CACHE_DIR/sire.run
  - git clone https://github.com/michellab/BioSimSpaceUnitTests $TEST_DIR

# Install BioSimSpace into the Sire application.
install:
  - cd python
  - $SIRE_DIR/bin/python setup.py install

# Run the BioSimSpace test suite.
script:
  - cd $TEST_DIR
  - $SIRE_DIR/bin/pytest tests -v

after_success:
  - echo "Congratulations - everything worked :-)
