# Pipeline to build the latest version of BioSimSpace by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'biosimspace-devel:latest'
# corresponds to the right place to start...

trigger:
- devel

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    # login to docker and get the last successful biosimspace-devel build
    docker login -u $id -p $pswd
    docker pull biosimspace/biosimspace-devel:latest

    # ensure the last known safe state is saved on docker
    docker tag biosimspace/biosimspace-devel:latest biosimspace/biosimspace-devel:last
    docker push biosimspace/biosimspace-devel:last
  env:
    pswd: $(dockerPassword)
    id: $(dockerId)
  displayName: 'Pull biosimspace-devel:latest'
- script: |
    docker login -u $id -p $pswd

    # now build the latest version of devel, starting from the last point
    cd docker/biosimspace-pipeline-devel && docker build -f Dockerfile -t biosimspace/biosimspace-devel:latest . && cd - && docker push biosimspace/biosimspace-devel:latest
  env:
    pswd: $(dockerPassword)
    id: $(dockerId)
  displayName: 'Build BioSimSpace'
- script: |
    # now perform the tests - do this before packaging and deploy
    cd docker/test-devel && docker build -f Dockerfile -t biosimspace/test-devel:latest . && cd -
  displayName: 'Run BioSimSpace tests'
- script: |
    # if the test were successful then create a binary installer package
    cd docker/package-devel && docker build -f Dockerfile -t biosimspace/package-devel:latest . && cd -
  displayName: 'Package BioSimSpace into a binary'
- script: |
    # now build the documentation and update the website
    cd docker/document-devel && docker build -f Dockerfile --build-arg github_token="$github_token" --build-arg github_email="$github_email" . && cd -
  env:
    github_token: $(githubToken)
    github_email: $(githubEmail)
  displayName: 'Build documentation and update website'
- script: |
    # finally deploy the binary to an object store bucket identified by 'par_url'
    cd docker/deploy-devel && docker build -f Dockerfile --build-arg par_url=$par_url . && cd -
  env:
    par_url: $(parURL)
  displayName: 'Deploy binary to biosimspace.org'
