# Pipeline to build the latest version of BioSimSpace by starting from a docker
# image of a recent build. This avoids the (VERY) long build times if
# we start from scratch. You should ensure that 'biosimspace-devel:latest'
# corresponds to the right place to start...

trigger:
- devel

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    # now build the documentation and update the website
    cd docker/document-devel && docker build -f Dockerfile --build-arg github_token=$github_token . && cd -
  env:
    github_token: $(githubToken)
  displayName: 'Build documentation and update website'
